name: Node CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run lint
      - run: npm test
      - name: Upload Pages artifact
        if: github.ref == 'refs/heads/gh-pages'
        uses: actions/upload-pages-artifact@v1
        with:
          path: .
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/gh-pages'
        uses: actions/deploy-pages@v1
